copr-be: use stdin=DEVNULL when calling ansible-playbooks
This is the way around weird F39+ bug causing ansible-playbook failure:
ERROR: Ansible requires blocking IO on stdin/stdout/stderr. Non-blocking file handles detected: <stdin>

Fixes: https://github.com/fedora-copr/copr/issues/3018