Switch 'Fedora Archive' category to scan-primary-mirror
Scanning 'Fedora Archive' with the Python based scanner produces
following error for some time now:

/srv/pub/archive/fullfiletimelist-archive has changed since last run. Running umdl for Fedora Archive at Thu Jan 13 12:15:01 UTC 2022
Traceback (most recent call last):
  File "/usr/bin/mm2_update-master-directory-list", line 1122, in <module>
    sys.exit(main())
  File "/usr/bin/mm2_update-master-directory-list", line 1105, in main
    session, config, i['path'], category)
  File "/usr/bin/mm2_update-master-directory-list", line 970, in sync_directories_from_fullfiletimelist
    sync_category_directory(session, config, category, dirname, ctimes[dirname], file_dict, is_repo)
  File "/usr/bin/mm2_update-master-directory-list", line 617, in sync_category_directory
    session, config, relativeDName, D, category, 'repomd.xml')
  File "/usr/lib/python2.7/site-packages/mirrormanager2/lib/umdl.py", line 294, in make_repo_file_details
    yumrepo = rpmmd.repoMDObject.RepoMD('repoid', absolutepath)
  File "/usr/lib/python2.7/site-packages/rpmmd/repoMDObject.py", line 145, in __init__
    self.parse(srcfile)
  File "/usr/lib/python2.7/site-packages/rpmmd/repoMDObject.py", line 165, in parse
    for event, elem in parser:
  File "<string>", line 100, in next
  File "/usr/lib/python2.7/site-packages/rpmmd/misc.py", line 150, in read
    return self.checksums.read(self._fo, size)
  File "/usr/lib/python2.7/site-packages/rpmmd/misc.py", line 104, in read
    self.update(data)
  File "/usr/lib/python2.7/site-packages/rpmmd/misc.py", line 100, in update
    sumalgo.update(data.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 273: ordinal not in range(128)
umdl for Fedora Archive returned non-zero. Something failed. Please check umdl.log. Thu Jan 13 12:17:45 UTC 2022

The new tool, scan-primary-mirror, does not have this problem and
I wanted to switch to it for some time already.

With this the error is gone and the new tool is used.

Signed-off-by: Adrian Reber <adrian@lisas.de>